### PR TITLE
define root in strict mode for browsers

### PR DESCRIPTION
**Pull request by DanielRuf**
Not sure if this is the right way but all templates did not solve my issue.

Related:
https://github.com/jonathantneal/svg4everybody/issues/111
https://github.com/jonathantneal/svg4everybody/issues/162

This provides a fix for #19 for environments in strict mode.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Not sure if this is the right way but all templates did not solve my issue.

**Comment by DanielRuf** [comment]
Related:
https://github.com/jonathantneal/svg4everybody/issues/111
https://github.com/jonathantneal/svg4everybody/issues/162

**Comment by bebraw** [comment]
Maybe `unit.hbs` needs this too. You could check the other templates.

I'm ok with the change as it seems safe enough.

**Comment by DanielRuf** [comment]
> Maybe unit.hbs needs this too. You could check the other templates.

Right, I thought abut this, that the other templates would need this too. I will check this and push new commits this evening or weekend.

**Comment by bebraw** [comment]
> Right, I thought abut this, that the other templates would need this too. I will check this and push new commits this evening or weekend.

Ok, cool.

If you want, I can add you as a maintainer to the project. I'm not using it anywhere at the moment.

I wanted to push this below the official umd organization but that never went forward. That would be the right place for this package.

**Comment by DanielRuf** [comment]
I've pushed a new commit. This should fix some libraries when they were transpiled with gulp-babel, webpack or something else and root is undefined.

**Comment by bebraw** [comment]
Thanks! Included in `0.8.0`.

Let me know if you want me to add you to the project as a maintainer.

**Comment by DanielRuf** [comment]
> Let me know if you want me to add you to the project as a maintainer.

You can add me as a maintainer. Releases and commits of me are generally signed, jfyi.

**Comment by bebraw** [comment]
@DanielRuf Done. Let me know of your npm nick and I'll add you there too.

**Comment by DanielRuf** [comment]
https://www.npmjs.com/~danielruf

**Comment by bebraw** [comment]
@DanielRuf Done. It was the casing. 👍

**Pull request merged**
